### PR TITLE
Add hr player name on tooltip

### PR DESCRIPTION
**Pull request by Graussak**
Simple add the designated player for the HR (if provided on softres.it) . 

When class unknown (ie player is not register on softres, or with a different name):
image

When class known:
image

### CODE REVIEW

**Comment by papa-smurf** [comment]
Hey @Graussak, really appreciate your contribution. I'm currently knee-deep in the GDKP so I can't switch to this PR just yet sadly!

**Comment by papa-smurf** [comment]
Hey @Graussak, I thought I could quickly merge your PR today but since it hasn't been tested (the `IDIsHardReserved` method is removed for example even though it's still used) that means I have to do full testing etc myself which is not something I can afford doing at the moment. I will add this to my todo list and add it when I'm done with GDKP.

**Comment by Graussak** [comment]
Thanks!
You're right mb, I did not set up correctly my IDE for lua so noone yell at me!
I put back the method.
A little weird to now have: linkIsHardReserved, IDIsHardReserved and getHardReservedByLink but not that important.

**Comment by papa-smurf** [comment]
Hi @Graussak , this was included in the latest update. Thank you for your contribution!

**Pull request closed without merging**
