### PR TITLE
Adding Blizzard Lookalike roll window

### PR DESCRIPTION
**Pull request by mullerdavid**
Adding an alternative look for roll ui, can be configured in settings.
kép

### CODE REVIEW

**Comment by papa-smurf** [comment]
Loving it! I'll test it soon and leave feedback.

Some questions meanwhile:
- Did you test it with longer item names like `Merciless Gladiator's Crossbow of the Phoenix`?
- Did you test it on classic era?
- Does the window get wider based on the number of buttons much like the original? Or is it limited to two buttons?

**Comment by mullerdavid** [comment]
> Loving it! I'll test it soon and leave feedback.
> 
> Some questions meanwhile:
> 
>     * Did you test it on classic era?

Didn't test it on classic era either, but I don't remember any API that should break it. Should be tested.

**Comment by mullerdavid** [comment]
>     * Did you test it with longer item names like `Merciless Gladiator's Crossbow of the Phoenix`?

The text works like on blizzard ui, tried to copy most parts from there. It gets trimmed if too long. You can mouseover the item and get tooltip if ambigious.

>     * Does the window get wider based on the number of buttons much like the original? Or is it limited to two buttons?

3 buttons can fit without growing, after that the buttons grow downward in my implementation. 

kép

**Comment by mullerdavid** [comment]
kép

**Comment by papa-smurf** [comment]
Hey @mullerdavid

I will put this pull request on hold for a bit. It's awesome, but I do need to do quite some rewriting before I can accept it. This is mostly related to styiling and structure, but also the fact that multiple guilds are running with 4+ roll buttons with larger identifiers ("BIS, Major Upgrade, Minor Upgrade, OS, PVP" for example) which looks quite odd in the current setup.

The reason why I put it on hold is because of something I recently posted on our discord:
image

Don't worry, I will not forget about this PR and will merge it as soon as possible!

**Comment by papa-smurf** [comment]
Hey @mullerdavid. I've given this much thought and, despite it being cool as hell, have decided that I'm not willing to merge this. Please don't let this deter you from future contributions. Any new functionality I add is something I will have to test and maintain indefinitely across the three major versions and all future patches, which is why I've become more selective about what I add and am willing to support.

Thank you for your understanding

**Pull request closed without merging**
