### PR TITLE
Close Static Popup when Auto Confirming Loot

### PR DESCRIPTION
**Pull request by orionshock**
Close the static popup when auto looting.
Word wrapping tooltip is enhancement.
Link Wrangler support would be nice.

### CODE REVIEW

**Comment by papa-smurf** [comment]
Hi! I am completly oblivious when it comes to LinkWrangler, but when looking at the documentation it seems to require a bit more than simply using `GL.OnTooltipSetItemFunc = function(Tooltip)`. Can you explain?

**Comment by papa-smurf** [comment]
Also: I'm not quite sure if word wrapping is an improvement:
image
vs
image

**Comment by orionshock** [comment]
> Hi! I am completly oblivious when it comes to LinkWrangler, but when looking at the documentation it seems to require a bit more than simply using `GL.OnTooltipSetItemFunc = function(Tooltip)`. Can you explain?

Yes it requires a shim from the other side to actually implement. All that's really needed from the source addon is to expose the tooltip function somewhere.

I'm compiling a series of them before sending them over to link wrangler. This is the one for Gargul:



            LinkWrangler.RegisterCallback(

                "Gargul.OnTooltipSetItemFunc",

                function(tip)
                    Gargul.OnTooltipSetItemFunc(tip)
                end,

                "item"
            )

**Comment by orionshock** [comment]
> Also: I'm not quite sure if word wrapping is an improvement:

vs

image

Granted, having the person in charge of TMB to in an edit the notation to add a line break _might_ be a better option, easier said then done.

**Comment by papa-smurf** [comment]
> 

Honestly the wordwrap seems like a nuisance to 99% of the userbase and only convenient for that 1% that has people in charge of notes who quite frankly shouldn't be in charge of notes ^^

`Bis for all casters without Val'anyr`, done!

**Comment by papa-smurf** [comment]
> > Hi! I am completly oblivious when it comes to LinkWrangler, but when looking at the documentation it seems to require a bit more than simply using `GL.OnTooltipSetItemFunc = function(Tooltip)`. Can you explain?
> 
> Yes it requires a shim from the other side to actually implement. All that's really needed from the source addon is to expose the tooltip function somewhere.
> 
> I'm compiling a series of them before sending them over to link wrangler. This is the one for Gargul:
> 
> ```
>         LinkWrangler.RegisterCallback(
> 
>             "Gargul.OnTooltipSetItemFunc",
> 
>             function(tip)
>                 Gargul.OnTooltipSetItemFunc(tip)
>             end,
> 
>             "item"
>         )
> ```

I'd have to see this in action then, because I suspect that when peopel see Gargul pop up anywhere in an error they'll come my way and that's something I'd like to prevent.

Can you send me a version of this link wrangler and what it should do so that I can test it in-game? I'm not trying to be ungrateful btw, I simply have too much on my plate to do my own deep-dive in this.

**Comment by orionshock** [comment]
> > 
> 
> Honestly the wordwrap seems like a nuisance to 99% of the userbase and only convenient for that 1% that has people in charge of notes who quite frankly shouldn't be in charge of notes ^^
> 
> `Bis for all casters without Val'anyr`, done!

fair point :)

**Comment by orionshock** [comment]
> I'd have to see this in action then, because I suspect that when peopel see Gargul pop up anywhere in an error they'll come my way and that's something I'd like to prevent.
> 
> Can you send me a version of this link wrangler and what it should do so that I can test it in-game? I'm not trying to be ungrateful btw, I simply have too much on my plate to do my own deep-dive in this.

https://www.curseforge.com/wow/addons/link-wrangler-1-7

It should look like the picture above - that tooltip is from LinkWrangler (with atlas loot and auctionator additions). As for that code snippet i put in previously, as long as link wrangler and gargul are loaded it should work with out issue. I've been running it for several weeks with out any problems. Tho, it could do with some more error checking to see if the tables are present first before firing off.

I haven't done any specific work to/for LinkWrangler yet to implement it, just have it in a addon that I test code from.

**Comment by papa-smurf** [comment]
@orionshock I'll include the exposed tooltip function in Gargul's next release (scheduled for Mo/Tu), thank you for your contribution! :)

**Pull request closed without merging**
